name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Create LFE Library Project
      run: echo TBD
    - name: Create LFE Main Project
      run: echo TBD
    - name: Run LFE Main Project's Script
      run: echo TBD
    - name: Create LFE/OTP Application Project
      run: echo TBD
    - name: Create LFE/OTP Release Project
      run: echo TBD
